=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::AcceptedCountriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AcceptedCountriesApi' do
  before do
    # run before each test
    @api_instance = Marqeta::AcceptedCountriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AcceptedCountriesApi' do
    it 'should create an instance of AcceptedCountriesApi' do
      expect(@api_instance).to be_instance_of(Marqeta::AcceptedCountriesApi)
    end
  end

  # unit tests for get_acceptedcountries
  # Lists all accepted countries
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of accepted countries to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :name Name
  # @option opts [Boolean] :whitelist Whitelist
  # @option opts [String] :search_type Search type
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @option opts [String] :sort_by Sort order
  # @return [AcceptedCountriesListResponse]
  describe 'get_acceptedcountries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_acceptedcountries_token
  # Returns a specific accepted country
  # @param token Accepted country token
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @return [AcceptedCountriesModel]
  describe 'get_acceptedcountries_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
