=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::BusinessesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BusinessesApi' do
  before do
    # run before each test
    @api_instance = Marqeta::BusinessesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BusinessesApi' do
    it 'should create an instance of BusinessesApi' do
      expect(@api_instance).to be_instance_of(Marqeta::BusinessesApi)
    end
  end

  # unit tests for get_businesses
  # Lists all businesses
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of users to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :business_name_dba Business name DBA
  # @option opts [String] :business_name_legal Business name legal
  # @option opts [String] :search_type Search type
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @option opts [String] :sort_by Sort order
  # @return [BusinessCardHolderListResponse]
  describe 'get_businesses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_businesses_parenttoken_children
  # Lists all children of a parent business
  # @param parent_token Token of parent business
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of users to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @option opts [String] :sort_by Sort order
  # @return [UserCardHolderListResponse]
  describe 'get_businesses_parenttoken_children test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_businesses_token
  # Returns a specific business
  # @param token Business token
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @return [BusinessCardHolderResponse]
  describe 'get_businesses_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_businesses_token_notes
  # Lists business notes
  # @param token Business token
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start_index Start index
  # @option opts [Integer] :count Number of notes to retrieve
  # @option opts [String] :created_by Created by
  # @option opts [String] :created_by_user_role Comma-delimited list of created by user roles
  # @option opts [Boolean] :include_private Include private notes and private fields in note response
  # @option opts [String] :search_type Search type
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @option opts [String] :sort_by Sort order
  # @return [CardHolderNoteListResponse]
  describe 'get_businesses_token_notes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_businesses_token_ssn
  # Returns a specific business proprietor&#39;s SSN
  # @param token Business token
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :full_ssn 
  # @return [SsnResponseModel]
  describe 'get_businesses_token_ssn test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_businesses
  # Creates a business
  # @param [Hash] opts the optional parameters
  # @option opts [BusinessCardholder] :body 
  # @return [BusinessCardHolderResponse]
  describe 'post_businesses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_businesses_lookup
  # Returns a specific business
  # @param [Hash] opts the optional parameters
  # @option opts [DDARequest] :body 
  # @return [BusinessCardholder]
  describe 'post_businesses_lookup test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_businesses_token_notes
  # Creates a note for a business
  # @param token Business token
  # @param [Hash] opts the optional parameters
  # @option opts [CardholderNoteRequestModel] :body 
  # @return [CardholderNoteResponseModel]
  describe 'post_businesses_token_notes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_businesses_token
  # Updates a specific business
  # @param token Business token
  # @param body Business object
  # @param [Hash] opts the optional parameters
  # @return [BusinessCardholder]
  describe 'put_businesses_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_businesses_token_notes_notestoken
  # Updates a specific note for a business
  # @param token Business token
  # @param notes_token Notes token
  # @param [Hash] opts the optional parameters
  # @option opts [CardholderNoteUpdateRequestModel] :body 
  # @return [CardholderNoteResponseModel]
  describe 'put_businesses_token_notes_notestoken test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
