=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::FeesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FeesApi' do
  before do
    # run before each test
    @api_instance = Marqeta::FeesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeesApi' do
    it 'should create an instance of FeesApi' do
      expect(@api_instance).to be_instance_of(Marqeta::FeesApi)
    end
  end

  # unit tests for get_fees
  # Lists all fees
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of fees to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @option opts [String] :sort_by Sort order
  # @return [FeeListResponse]
  describe 'get_fees test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_fees_token
  # Returns a specific fee
  # @param token Fee token
  # @param [Hash] opts the optional parameters
  # @return [Fee]
  describe 'get_fees_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_fees
  # Creates a fee
  # @param [Hash] opts the optional parameters
  # @option opts [FeeRequest] :body 
  # @return [Fee]
  describe 'post_fees test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_fees_token
  # Updates a specific fee
  # @param token Fee token
  # @param [Hash] opts the optional parameters
  # @option opts [FeeUpdateRequest] :body 
  # @return [Fee]
  describe 'put_fees_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
