=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::GpaOrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GpaOrdersApi' do
  before do
    # run before each test
    @api_instance = Marqeta::GpaOrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GpaOrdersApi' do
    it 'should create an instance of GpaOrdersApi' do
      expect(@api_instance).to be_instance_of(Marqeta::GpaOrdersApi)
    end
  end

  # unit tests for get_gpaorders_token
  # Returns a GPA order
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [GpaResponse]
  describe 'get_gpaorders_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_gpaorders_unloads
  # Lists all GPA returns
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of GPA unloads to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @option opts [String] :sort_by Sort order
  # @option opts [String] :user_token User token
  # @option opts [String] :business_token Business token
  # @option opts [String] :original_order_token Original order token
  # @return [GPAUnloadListResponse]
  describe 'get_gpaorders_unloads test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_gpaorders_unloads_unloadtoken
  # Returns a specific GPA return
  # @param unload_token Unload token
  # @param [Hash] opts the optional parameters
  # @return [GpaReturns]
  describe 'get_gpaorders_unloads_unloadtoken test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_gpaorders
  # Funds a user&#39;s GPA account
  # @param [Hash] opts the optional parameters
  # @option opts [GpaRequest] :body 
  # @return [GpaResponse]
  describe 'post_gpaorders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_gpaorders_unloads
  # Returns a GPA order
  # @param [Hash] opts the optional parameters
  # @option opts [UnloadRequestModel] :body 
  # @return [GpaReturns]
  describe 'post_gpaorders_unloads test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
