=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::MsaOrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MsaOrdersApi' do
  before do
    # run before each test
    @api_instance = Marqeta::MsaOrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MsaOrdersApi' do
    it 'should create an instance of MsaOrdersApi' do
      expect(@api_instance).to be_instance_of(Marqeta::MsaOrdersApi)
    end
  end

  # unit tests for get_msaorders_token
  # Returns an MSA order 
  # @param token Order token
  # @param [Hash] opts the optional parameters
  # @return [MsaOrderResponse]
  describe 'get_msaorders_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_msaorders_unloads
  # Lists all MSA unloads
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of MSA unloads to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :sort_by Sort order
  # @option opts [String] :user_token User token
  # @option opts [String] :business_token Business token
  # @option opts [String] :original_order_token Original order token
  # @return [MSAUnloadListResponse]
  describe 'get_msaorders_unloads test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_msaorders_unloads_unloadtoken
  # Returns a specific MSA unload
  # @param unload_token Unload token
  # @param [Hash] opts the optional parameters
  # @return [MsaReturns]
  describe 'get_msaorders_unloads_unloadtoken test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_msaorders
  # Creates a merchant-specific account order
  # @param [Hash] opts the optional parameters
  # @option opts [MsaOrderRequest] :body 
  # @return [MsaOrderResponse]
  describe 'post_msaorders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_msaorders_unloads
  # Returns an MSA order
  # @param [Hash] opts the optional parameters
  # @option opts [MsaUnloadRequestModel] :body 
  # @return [MsaReturns]
  describe 'post_msaorders_unloads test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_msaorders_token
  # Updates a specific merchant-specific account order
  # @param token Order token
  # @param [Hash] opts the optional parameters
  # @option opts [MsaOrderUpdateRequest] :body 
  # @return [MsaOrderResponse]
  describe 'put_msaorders_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
