=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::OfferOrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OfferOrdersApi' do
  before do
    # run before each test
    @api_instance = Marqeta::OfferOrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OfferOrdersApi' do
    it 'should create an instance of OfferOrdersApi' do
      expect(@api_instance).to be_instance_of(Marqeta::OfferOrdersApi)
    end
  end

  # unit tests for get_offerorders_token
  # Returns a purchase order for a specific offer
  # @param token Order token
  # @param [Hash] opts the optional parameters
  # @return [OfferOrderResponse]
  describe 'get_offerorders_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_offerorders
  # Creates an offer order
  # @param [Hash] opts the optional parameters
  # @option opts [OfferOrderRequest] :body 
  # @return [OfferOrderResponse]
  describe 'post_offerorders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
