=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::OffersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OffersApi' do
  before do
    # run before each test
    @api_instance = Marqeta::OffersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OffersApi' do
    it 'should create an instance of OffersApi' do
      expect(@api_instance).to be_instance_of(Marqeta::OffersApi)
    end
  end

  # unit tests for get_offers
  # Lists all offers
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of items to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @option opts [String] :sort_by Sort order
  # @return [OfferListResponse]
  describe 'get_offers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_offers_token
  # Returns a specific offer
  # @param token Offer token
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Comma-delimited list of fields to return (e.g. field_1,field_2,..). Leave blank to return all fields.
  # @return [OfferResponseModel]
  describe 'get_offers_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_offers
  # Creates an offer
  # @param [Hash] opts the optional parameters
  # @option opts [OfferModel] :body 
  # @return [OfferResponseModel]
  describe 'post_offers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_offers_token
  # Updates an offer
  # @param token Offer token
  # @param [Hash] opts the optional parameters
  # @option opts [OfferUpdateModel] :body 
  # @return [OfferResponseModel]
  describe 'put_offers_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
