=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::PinsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PinsApi' do
  before do
    # run before each test
    @api_instance = Marqeta::PinsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PinsApi' do
    it 'should create an instance of PinsApi' do
      expect(@api_instance).to be_instance_of(Marqeta::PinsApi)
    end
  end

  # unit tests for post_pins_controltoken
  # Creates a new control token for a PIN
  # Creates a new control token for a PIN, for the specified card for PIN debit or ATM transactions,or to allow for a pin to be revealed to authorized callers.
  # @param [Hash] opts the optional parameters
  # @option opts [ControlTokenRequest] :body 
  # @return [ControlTokenResponse]
  describe 'post_pins_controltoken test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_pins
  # Updates the PIN control token
  # Updates a PIN identified by its control token.
  # @param [Hash] opts the optional parameters
  # @option opts [PinRequest] :body 
  # @return [nil]
  describe 'put_pins test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reveal_pins
  # Updates the PIN-reveal control token
  # Reveals pin for card associated with given control token.
  # @param [Hash] opts the optional parameters
  # @option opts [PinRevealRequest] :body 
  # @return [nil]
  describe 'reveal_pins test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
