=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Marqeta::ProgramReserveApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProgramReserveApi' do
  before do
    # run before each test
    @api_instance = Marqeta::ProgramReserveApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProgramReserveApi' do
    it 'should create an instance of ProgramReserveApi' do
      expect(@api_instance).to be_instance_of(Marqeta::ProgramReserveApi)
    end
  end

  # unit tests for deposit
  # @param [Hash] opts the optional parameters
  # @option opts [ProgramReserveDepositRequest] :body 
  # @return [nil]
  describe 'deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_program_reserve_deposits
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of items to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :sort_by Sort order
  # @return [nil]
  describe 'get_program_reserve_deposits test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_programreserve_balances
  # Returns the latest balance in the program reserve account
  # @param [Hash] opts the optional parameters
  # @return [ProgramReserveAccountBalance]
  describe 'get_programreserve_balances test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_programreserve_transactions
  # Returns a list of program reserve transactions (credits and debits)
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Number of items to retrieve
  # @option opts [Integer] :start_index Start index
  # @option opts [String] :sort_by Sort order
  # @option opts [String] :body Type
  # @return [ProgramReserveTransactionListResponse]
  describe 'get_programreserve_transactions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_programreserve_transactions
  # Credits or debits the program reserve account
  # @param [Hash] opts the optional parameters
  # @option opts [ProgramReserveTransactionRequest] :body 
  # @return [ProgramReserveTransactionResponse]
  describe 'post_programreserve_transactions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
