=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Marqeta::ClearingAndSettlement
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Marqeta::ClearingAndSettlement do
  let(:instance) { Marqeta::ClearingAndSettlement.new }

  describe 'test an instance of ClearingAndSettlement' do
    it 'should create an instance of ClearingAndSettlement' do
      expect(instance).to be_instance_of(Marqeta::ClearingAndSettlement)
    end
  end
  describe 'test attribute "overdraft_destination"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["GPA", "MSA", "MERCHANT_CAMPAIGN_ACCOUNT", "GLOBAL_OVERDRAFT_ACCOUNT"])
      # validator.allowable_values.each do |value|
      #   expect { instance.overdraft_destination = value }.not_to raise_error
      # end
    end
  end

end
