=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Marqeta::DigitalWalletAndroidPayProvisionRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Marqeta::DigitalWalletAndroidPayProvisionRequest do
  let(:instance) { Marqeta::DigitalWalletAndroidPayProvisionRequest.new }

  describe 'test an instance of DigitalWalletAndroidPayProvisionRequest' do
    it 'should create an instance of DigitalWalletAndroidPayProvisionRequest' do
      expect(instance).to be_instance_of(Marqeta::DigitalWalletAndroidPayProvisionRequest)
    end
  end
  describe 'test attribute "card_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "device_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["MOBILE_PHONE", "WATCH", "TABLET"])
      # validator.allowable_values.each do |value|
      #   expect { instance.device_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "provisioning_app_version"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "wallet_account_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "device_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
