=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Marqeta::ImagesSignature
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Marqeta::ImagesSignature do
  let(:instance) { Marqeta::ImagesSignature.new }

  describe 'test an instance of ImagesSignature' do
    it 'should create an instance of ImagesSignature' do
      expect(instance).to be_instance_of(Marqeta::ImagesSignature)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
