=begin
#Marqeta Core API

#Simplified management of your payment programs

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Marqeta::NetworkFeeModel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Marqeta::NetworkFeeModel do
  let(:instance) { Marqeta::NetworkFeeModel.new }

  describe 'test an instance of NetworkFeeModel' do
    it 'should create an instance of NetworkFeeModel' do
      expect(instance).to be_instance_of(Marqeta::NetworkFeeModel)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ISSUER_FEE", "SWITCH_FEE", "PINDEBIT_ASSOC_FEE", "ACQUIRER_FEE", "INTERCHANGE_FEE", "CUR_CONV_CARDHOLDER_FEE", "CUR_CONV_ISSUER_FEE", "CROSS_BORDER_ISSUER_FEE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "credit_debit"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["C", "D"])
      # validator.allowable_values.each do |value|
      #   expect { instance.credit_debit = value }.not_to raise_error
      # end
    end
  end

end
